### ISSUE TITLE
[Job Opening] Full time developers or interns

### ISSUE THREAD

**Issue by xianyi** [OpenMathLib/OpenBLAS#1007]
Hi all,

I just founded a startup, [PerfXLab](http://perfxlab.com/), focusing on high performance libraries and frameworks for deep learning on embedded system and cloud. 

Responsibility:
* Contribute to OpenBLAS and other open source projects.
* Implement and optimize machine learning libraries and frameworks.

Qualifications:
* Experienced with Linux
* Good C/C++ programming
* HPC or Machine learning background (optional)
* Experienced with Assembly, GPU(CUDA/OpenCL), or FPGA (optional)

Location: Beijing
Expected Salary: RMB 18K-30K/month

If you are interested, please contact me via email: xianyi@perfxlab.com

Xianyi

**Comment by martin-frbg** [comment]
s/found/founded/ surely ? Best of luck with your enterprise.

**Comment by xianyi** [comment]
@martin-frbg Thank you for correcting my error.
