### ISSUE TITLE
What about precision control in OpenBLAS?

### ISSUE THREAD

**Issue by EpsilonQM** [OpenMathLib/OpenBLAS#606]
1. Subj. 

There are always errors. At least there are errors of rounding in finite-digital representation of numbers. And they raise, sometimes extremely fast, in result of long sequential calculations.

For example:
http://www.cs.berkeley.edu/~wkahan/Mindless.pdf
http://www.cs.berkeley.edu/~wkahan/Math128/M128Bsoln09Feb04.pdf

There are some situations cannot be solved correctly. I mean J.-M. Muller's recurrency first of all.

Well at least one could detect such emergency situations early if he had controlled the accuracy of representation and calculations especially.

In addition there are some ways of slowing the rise of errors by reordering the sequence of calculations. Is there some 'precise BLAS' using this ways with precision control?

Sometimes I need to inverse poor conditioned matrices so I'd love to have a BLAS with precision control and though more slow version of BLAS with error-minimised procedures.

Sorry for probably bad english.

**Comment by klaus-pototzky** [comment]
If you are having problems with precision, you can use FLENS ( https://github.com/michael-lehn/FLENS ). It has a generic BLAS and LAPACK implementation for most of the functions. 

You can combine it with the multi-precision library mpfr ( http://www.mathematik.uni-ulm.de/~lehn/FLENS/flens/examples/lapack-geev.html#6 ) and increase the precision of the used datatype as needed.
