### ISSUE TITLE
make install-tests (feature request)

### ISSUE THREAD

**Issue by vincent-olivert-riera** [OpenMathLib/OpenBLAS#922]
Hello,

would it be possible to include one target in the Makefile in order to install the tests?

Thanks,

Vincent.

**Comment by xianyi** [comment]
Why do you want to install the tests?

**Comment by vriera** [comment]
In order to not copy them manually to the target. It's more handy if we can do something like "make install-tests" or something like that in order to have the tests installed into (for instance) /usr/share/openblas/{test,ctest,utest}/
